import type { InstrumentTextBundle } from './types';

// Published English wording for each instrument, entered as content — never
// generated from the Russian (see ADR-006 and docs/I18N.md). Item order
// matches ru.ts position-for-position for readability and to keep the two
// content files easy to diff; nothing in the scoring depends on it, since
// `reversed` / `thresholds` (in lib/clinicalTests.ts) already index into
// this same shared order for both locales.
//
// Sourced against publicly available reproductions of each published,
// public-domain instrument: PHQ-9 and GAD-7 (Pfizer/Spitzer, Kroenke,
// Williams), ASRS-v1.1 (WHO/Kessler et al.), PSS-10 (Cohen — via Carnegie
// Mellon's own Laboratory for the Study of Stress, Immunity and Disease),
// WHO-5 (WHO Regional Office for Europe, cdn.who.int), ISI (Bastien,
// Vallières & Morin), CES-D (Radloff), PHQ-15 (Kroenke, Spitzer & Williams),
// RSES (Rosenberg), CFQ (Broadbent, Cooper, FitzGerald & Parkes), and MDQ
// (Hirschfeld et al.).

const FREQ_5 = ['Never', 'Rarely', 'Sometimes', 'Often', 'Very often'];
const PHQ_SCALE = ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'];
const PSS_SCALE = ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often'];

export const en: InstrumentTextBundle = {
    asrs: {
        name: 'ASRS-v1.1 · ADHD screener',
        short: 'ADHD',
        intro: "Part A of the WHO's adult self-report scale — the six questions most predictive of adult ADHD.",
        period: 'Over the last 6 months',
        questions: [
            'How often do you have trouble wrapping up the final details of a project, once the challenging parts have been done?',
            'How often do you have difficulty getting things in order when you have to do a task that requires organization?',
            'How often do you have problems remembering appointments or obligations?',
            'When you have a task that requires a lot of thought, how often do you avoid or delay getting started?',
            'How often do you fidget or squirm with your hands or feet when you have to sit down for a long time?',
            'How often do you feel overly active and compelled to do things, like you were driven by a motor?',
        ],
        optionText: FREQ_5,
        bandLabels: ['Few indications', 'Symptoms consistent with ADHD'],
        note: 'The score counts how many answers cross their own threshold. 4 or more is the result at which an in-person evaluation is usually recommended.',
    },
    phq9: {
        name: 'PHQ-9 · mood',
        short: 'Mood',
        intro: 'Nine items on signs of low mood. One of the most widely used screeners in the world.',
        period: 'Over the last 2 weeks',
        questions: [
            'Little interest or pleasure in doing things',
            'Feeling down, depressed, or hopeless',
            'Trouble falling or staying asleep, or sleeping too much',
            'Feeling tired or having little energy',
            'Poor appetite or overeating',
            'Feeling bad about yourself — or that you are a failure, or have let yourself or your family down',
            'Trouble concentrating on things, such as reading or watching television',
            'Moving or speaking so slowly that other people could have noticed — or the opposite, being so fidgety or restless that you have been moving around a lot more than usual',
            'Thoughts that you would be better off dead, or of hurting yourself',
        ],
        optionText: PHQ_SCALE,
        bandLabels: ['Minimal symptoms', 'Mild symptoms', 'Moderate symptoms', 'Moderately severe symptoms', 'Severe symptoms'],
        note: 'From 10 points up, the result is usually worth discussing with a professional.',
    },
    gad7: {
        name: 'GAD-7 · anxiety',
        short: 'Anxiety',
        intro: 'Seven items on signs of generalized anxiety.',
        period: 'Over the last 2 weeks',
        questions: [
            'Feeling nervous, anxious, or on edge',
            'Not being able to stop or control worrying',
            'Worrying too much about different things',
            'Trouble relaxing',
            'Being so restless that it is hard to sit still',
            'Becoming easily annoyed or irritable',
            'Feeling afraid as if something awful might happen',
        ],
        optionText: PHQ_SCALE,
        bandLabels: ['Minimal anxiety', 'Mild anxiety', 'Moderate anxiety', 'Severe anxiety'],
        note: 'From 10 points up, the result is usually worth discussing with a professional.',
    },
    isi: {
        name: 'ISI · sleep quality',
        short: 'Sleep',
        intro: "Insomnia Severity Index: how disrupted your sleep is, and how much it's affecting your day.",
        period: 'Over the last 2 weeks',
        questions: [
            'Difficulty falling asleep',
            'Difficulty staying asleep (waking up during the night)',
            'Waking up too early',
            'How satisfied are you with your current sleep?',
            'How much do sleep problems interfere with your daily life?',
            'How noticeable is it to others that your sleep problems are affecting you?',
            'How worried are you about your sleep?',
        ],
        optionText: ['Not at all', 'A little', 'Moderately', 'A lot', 'Very much'],
        bandLabels: ['No clinically significant insomnia', 'Subthreshold insomnia', 'Moderate insomnia', 'Severe insomnia'],
    },
    pss10: {
        name: 'PSS-10 · perceived stress',
        short: 'Stress',
        intro: 'Ten questions about how unpredictable and unmanageable life has felt.',
        period: 'Over the last month',
        questions: [
            'How often have you been upset because of something that happened unexpectedly?',
            'How often have you felt that you were unable to control the important things in your life?',
            'How often have you felt nervous and stressed?',
            'How often have you felt confident about your ability to handle your personal problems?',
            'How often have you felt that things were going your way?',
            'How often have you found that you could not cope with all the things that you had to do?',
            'How often have you been able to control irritations in your life?',
            'How often have you felt that you were on top of things?',
            'How often have you been angered because of things that were outside your control?',
            'How often have you felt difficulties were piling up so high that you could not overcome them?',
        ],
        optionText: PSS_SCALE,
        bandLabels: ['Low perceived stress', 'Moderate perceived stress', 'High perceived stress'],
    },
    who5: {
        name: 'WHO-5 · well-being',
        short: 'Well-being',
        intro: 'Five short statements about how you have been feeling. Here, a higher score is better.',
        period: 'Over the last 2 weeks',
        questions: [
            'I have felt cheerful and in good spirits',
            'I have felt calm and relaxed',
            'I have felt active and vigorous',
            'I woke up feeling fresh and rested',
            'My daily life has been filled with things that interest me',
        ],
        optionText: ['At no time', 'Some of the time', 'Less than half of the time', 'More than half of the time', 'Most of the time', 'All of the time'],
        bandLabels: ['Low well-being', 'Reduced well-being', 'Normal well-being', 'High well-being'],
        note: 'Here a high score is a good sign. Below 50 is usually taken as a reason to look closer.',
    },
    asrs18: {
        name: 'ASRS-v1.1 · full scale (18 questions)',
        short: 'ADHD, full',
        intro: "The WHO's full self-report scale: inattention and hyperactivity-impulsivity. The first six questions are the short screener itself.",
        period: 'Over the last 6 months',
        questions: [
            'How often do you have trouble wrapping up the final details of a project, once the challenging parts have been done?',
            'How often do you have difficulty getting things in order when you have to do a task that requires organization?',
            'How often do you have problems remembering appointments or obligations?',
            'When you have a task that requires a lot of thought, how often do you avoid or delay getting started?',
            'How often do you fidget or squirm with your hands or feet when you have to sit down for a long time?',
            'How often do you feel overly active and compelled to do things, like you were driven by a motor?',
            'How often do you make careless mistakes when you have to work on a boring or difficult project?',
            'How often do you have difficulty keeping your attention when you are doing boring or repetitive work?',
            'How often do you have difficulty concentrating on what people say to you, even when they are speaking to you directly?',
            'How often do you misplace or have difficulty finding things at home or at work?',
            'How often are you distracted by activity or noise around you?',
            'How often do you leave your seat in meetings or other situations in which you are expected to remain seated?',
            'How often do you feel restless or fidgety?',
            'How often do you have difficulty unwinding and relaxing when you have time to yourself?',
            'How often do you find yourself talking too much when you are in social situations?',
            "How often do you find yourself finishing the sentences of the people you are talking to, before they can finish them themselves?",
            'How often do you have difficulty waiting your turn in situations when turn taking is required?',
            'How often do you interrupt others when they are busy?',
        ],
        optionText: FREQ_5,
        bandLabels: ['Symptoms are weakly expressed', 'Moderate symptoms', 'Pronounced symptoms'],
        note: 'This counts the sum of all 18 answers. The separate 6-question short version is the validated screener, with a threshold of 4.',
    },
    cesd: {
        name: 'CES-D · depression scale (20 questions)',
        short: 'Depression',
        intro: 'The full Center for Epidemiologic Studies scale: mood, physical symptoms, relationships with others.',
        period: 'Over the last week',
        questions: [
            "I was bothered by things that usually don't bother me",
            'I did not feel like eating; my appetite was poor',
            'I felt that I could not shake off the blues even with help from my family or friends',
            'I felt that I was just as good as other people',
            'I had trouble keeping my mind on what I was doing',
            'I felt depressed',
            'I felt that everything I did was an effort',
            'I felt hopeful about the future',
            'I thought my life had been a failure',
            'I felt fearful',
            'My sleep was restless',
            'I was happy',
            'I talked less than usual',
            'I felt lonely',
            'People were unfriendly',
            'I enjoyed life',
            'I had crying spells',
            'I felt sad',
            'I felt that people disliked me',
            'I could not get "going"',
        ],
        optionText: ['Rarely (less than 1 day)', 'Some of the time (1–2 days)', 'Occasionally (3–4 days)', 'Most of the time (5–7 days)'],
        bandLabels: ['No significant symptoms', 'Mild symptoms', 'Moderate symptoms', 'Severe symptoms'],
        note: 'The classic cut-off is 16 points: above it, the result is usually worth discussing with a professional.',
    },
    cfq: {
        name: 'CFQ · cognitive failures (25 questions)',
        short: 'Slip-ups',
        intro: "A questionnaire about everyday lapses of attention and memory — forgotten names, misplaced things, \"walked in and forgot why\". Especially recognizable with ADHD.",
        period: 'Over the last 6 months',
        questions: [
            "Do you read something and find you haven't been thinking about it and must read it again?",
            'Do you find you forget why you went from one part of the house to the other?',
            'Do you fail to notice signposts on the road or in a building?',
            'Do you find you confuse right and left when giving directions?',
            'Do you bump into people?',
            "Do you find you forget whether you've turned off a light, or locked the door?",
            'Do you fail to hear people speaking to you when you are doing something else?',
            'Do you say something and then realize afterwards it might be taken as insulting?',
            'Do you fail to take in what is said to you because your mind is on something else?',
            'Do you lose your thread in a conversation because you got distracted?',
            "Do you find you can't remember where you put something?",
            'Do you accidentally throw away the thing you want and keep what you meant to throw away?',
            'Do you daydream when you ought to be listening to something?',
            "Do you find you forget people's names?",
            'Do you start doing one thing and then get distracted into doing something else, without meaning to?',
            "Do you find you can't quite remember something although it's on the tip of your tongue?",
            'Do you forget why you went into a shop?',
            'Do you drop things?',
            "Do you find you can't think of anything to say in a conversation?",
            'Do you forget what you were about to do a moment ago?',
            'Do you find you can\'t remember what you did the day before?',
            'Do you forget where you just put something down?',
            'Do you make mistakes doing familiar, routine things?',
            'Do you start reading something and fall asleep or lose track?',
            'Do you forget a planned meeting or errand?',
        ],
        optionText: FREQ_5,
        bandLabels: ['Slip-ups are rare', 'Usual level', 'Slip-ups are noticeable', 'Slip-ups interfere with everyday life'],
        note: "The scale has no hard clinical cut-off — it is more useful as a baseline: take it again in a couple of months and compare.",
    },
    phq15: {
        name: 'PHQ-15 · physical symptoms (15 questions)',
        short: 'Body',
        intro: 'How much physical symptoms have bothered you over the last month. Helps see where stress lands in the body.',
        period: 'Over the last month',
        questions: [
            'Stomach pain',
            'Back pain',
            'Pain in your arms, legs, or joints (knees, hips, etc.)',
            'Headaches',
            'Chest pain or discomfort',
            'Dizziness',
            'Fainting spells or feeling faint',
            'Feeling your heart pound or race',
            'Shortness of breath',
            'Constipation, loose bowels, or diarrhea',
            'Nausea, bloating, or indigestion',
            'Feeling tired or having low energy',
            'Trouble sleeping',
            'Pain or problems during sexual intercourse',
            'Menstrual cramps or other problems with your periods (if applicable)',
        ],
        optionText: ['Not bothered at all', 'Bothered a little', 'Bothered a lot'],
        bandLabels: ['Minimal severity', 'Low severity', 'Medium severity', 'High severity'],
    },
    rses: {
        name: 'RSES · self-esteem (10 questions)',
        short: 'Self-esteem',
        intro: "The Rosenberg scale — one of the most widely used measures of overall self-worth.",
        period: 'Generally, about yourself',
        questions: [
            'On the whole, I am satisfied with myself',
            'At times I think I am no good at all',
            'I feel that I have a number of good qualities',
            'I am able to do things as well as most other people',
            'I feel I do not have much to be proud of',
            'I certainly feel useless at times',
            "I feel that I'm a person of worth, at least on an equal plane with others",
            'I wish I could have more respect for myself',
            'All in all, I am inclined to feel that I am a failure',
            'I take a positive attitude toward myself',
        ],
        optionText: ['Strongly disagree', 'Disagree', 'Agree', 'Strongly agree'],
        bandLabels: ['Low self-esteem', 'Medium self-esteem', 'High self-esteem'],
        note: 'Here a high score is a good sign. Below 15 is usually taken as a sign of low self-esteem.',
    },
    mdq: {
        name: 'MDQ · mood swings (13 questions)',
        short: 'Mood swings',
        intro: 'A questionnaire about periods of unusual elevation — when energy, talkativeness and confidence were noticeably higher than usual.',
        period: 'At any time in your life',
        questions: [
            'Have there been periods when you felt so good or so hyper that other people thought you were not your normal self, or you were so hyper that you got into trouble?',
            'Have there been periods when you were so irritable that you shouted at people or started fights or arguments?',
            'Have there been periods when you felt much more self-confident than usual?',
            "Have there been periods when you got much less sleep than usual and found you didn't really miss it?",
            'Have there been periods when you were much more talkative or spoke much faster than usual?',
            "Have there been periods when thoughts raced through your head or you couldn't slow your mind down?",
            'Have there been periods when you were so easily distracted by things around you that you had trouble concentrating?',
            'Have there been periods when you had much more energy than usual?',
            'Have there been periods when you were much more active or did many more things than usual?',
            'Have there been periods when you were much more social or outgoing than usual, for example, you telephoned friends in the middle of the night?',
            'Have there been periods when you were much more interested in sex than usual?',
            'Have there been periods when you did things that were unusual for you, or that other people might have thought were excessive, foolish, or risky?',
            'Have there been periods when spending money got you or your family into trouble?',
        ],
        optionText: ['No', 'Yes'],
        bandLabels: ['Few indications', 'Many matches'],
        note: "A full screening also weighs two more conditions: whether these states happened at the same time, and whether they caused real problems. The count of \"yes\" answers on its own is only a reason to look closer.",
    },
};
